CREATE TABLE property_notes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  raw_text TEXT,
  postcode VARCHAR(20),
  city VARCHAR(100),
  access_instructions TEXT,
  confidence_score TINYINT,
  confidence_tip TEXT,
  parking_info TEXT,
  amenities TEXT
);

INSERT INTO property_notes (raw_text) VALUES
('<p><strong>Welcome to Willow Barn!</strong> This converted barn is nestled on a 300-acre working farm. Guests must enter through the second gate on the left. <em>Do not use the main farmhouse gate</em>. A lockbox (code 1284) is attached to the back fence post next to the recycling bins.</p><ul><li>Dogs allowed (2 max)</li><li>Wi-Fi, Smart TV, board games</li><li>BBQ and fire pit provided</li></ul><p>Private parking for 1 car on gravel drive. Additional vehicles may park on the grass paddock with prior approval.</p><p><strong>Postcode:</strong> BS40 5RT</p>'),
('<h2>Top-floor Apartment in Woolacombe</h2><p>This modern 2-bedroom apartment is located just 5 minutes from the beach. Access is via key safe (code: 7721), located to the right of the elevator. A lift is available for guests with mobility needs.</p><p>Parking is included for 1 vehicle in bay #23, located beneath the building. Additional parking is street-level and first come, first served.</p><p><strong>Amenities:</strong></p><ul><li>Washer/dryer</li><li>Dishwasher</li><li>Hair dryer</li><li>Fast fibre Wi-Fi</li></ul><p><strong>Postcode:</strong> EX34 7BN</p>'),
('<p><strong>Family-friendly farm stay!</strong> This 3-bed bungalow offers countryside peace with access to animals, a pond, and walking paths. Guests should check in at the main barn office. Entry is via coded padlock on the green gate (code: 9045).</p><p><em>Please note:</em> this is an active livestock farm. Children should be supervised at all times, especially near the electric fence line at the rear.</p><p>Parking is gravel-based with overflow parking by the feed barn. DO NOT block access to tractor path.</p><ul><li>2 stair gates, travel cot, and high chair available</li><li>Board games, kids DVDs, plastic crockery</li><li>No Wi-Fi – strong 4G signal (O2)</li></ul><p><strong>Postcode:</strong> BS48 1DF</p>'),
('<h3>Lakeview Lodge</h3><p>Guests are welcomed by a local host at the property. <strong>Please call 20 mins before arrival</strong> to ensure someone is available for handover.</p><p>Entry via key lock (code 3319) on the post next to the blue shed. Follow the stepping stones to the deck.</p><p>Parking: 2 spaces available in front of the main gate. <em>No street parking allowed.</em></p><p><strong>Amenities:</strong> Canoe, private jetty, hammock, gas BBQ, telescope</p><p>Weekly firewood bundles available from the shop at entrance lane.</p><p><strong>Postcode:</strong> RG9 3DQ</p>'),
('<p><strong>Georgian Townhouse in Bath</strong></p><p>This beautifully preserved 18th-century townhouse spans 4 floors with original stonework and sash windows. Entry is via key code (6677) for the front door and physical key inside for internal access.</p><p>Guests must collect a <strong>parking permit</strong> from the hallway upon entry and display in their windscreen (Zone B). Nearest public car park is 5 mins away on Charlotte Street.</p><p>Steps are narrow and uneven — <em>not suitable for guests with mobility concerns</em>.</p><ul><li>4-poster bed in master</li><li>Stone fireplace, dining for 6</li><li>Flat screen TV, but no Wi-Fi due to historic listing</li></ul><p><strong>Postcode:</strong> BA1 2PH</p>');